Repository labseu2-workout-tracker/client, pull requests merged in 2019-09, with the labels that each got.

#20 Aboutus
  workout-tracker/public/index.html
  workout-tracker/src/App.css
  workout-tracker/src/App.js
  workout-tracker/src/assets/avatar/benjamin.jpg
  workout-tracker/src/assets/avatar/gym.jpg
  workout-tracker/src/assets/avatar/kelechi.jpg
  workout-tracker/src/assets/avatar/matt.jpg
  workout-tracker/src/assets/avatar/remi.jpg
  workout-tracker/src/assets/avatar/sean.jpg
  workout-tracker/src/assets/avatar/tale.jpg
  workout-tracker/src/assets/avatar/tigran.jpg
  workout-tracker/src/assets/avatar/wasiu.jpg
  workout-tracker/src/assets/avatar/yusuf.jpg
  workout-tracker/src/components/MainNavBar/MainNavBar.js
  workout-tracker/src/views/AboutUs/AboutUs.css
  workout-tracker/src/views/AboutUs/AboutUs.js
Labels: Frontend

#24 Contact site
  workout-tracker/src/views/ContactPage/ContactPage.js
Labels: Frontend

#27 Settings Page responsive design
  workout-tracker/src/store/actions/settingActions.js
  workout-tracker/src/views/Settings/Settings.js
  workout-tracker/src/views/Settings/settings.css
Labels: Frontend

#30 Add pull request format
  .github/pull_request_template.md
  package-lock.json
Labels: enhancement

#28 Auth optimization
  workout-tracker/src/App.css
  workout-tracker/src/App.js
  workout-tracker/src/components/Button/Button.css
  workout-tracker/src/views/Auth/Auth.css
  workout-tracker/src/views/Auth/Login.js
  workout-tracker/src/views/Auth/Signup.js
  workout-tracker/src/views/UserPage/UserPage.css
  workout-tracker/src/views/UserPage/UserPage.js
Labels: Frontend, bug

#34 View all workouts
  workout-tracker/src/App.js
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.js
  workout-tracker/src/store/actions/workoutsActions.js
  workout-tracker/src/views/AboutUs/AboutUs.css
  workout-tracker/src/views/LandingPage/LandingPage.css
  workout-tracker/src/views/Workouts/Workouts.js
Labels: Frontend

#33 Axios with authentication and fixed Exercise bug
  workout-tracker/src/App.js
  workout-tracker/src/components/Exercises/AllExercises.js
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.js
  workout-tracker/src/components/Watch/Watch.js
  workout-tracker/src/index.js
  workout-tracker/src/store/actions/workoutsActions.js
  workout-tracker/src/store/axiosWithAuth.js
  workout-tracker/src/store/reducers/exercises.js
  workout-tracker/src/store/reducers/workouts.js
  workout-tracker/src/views/ExerciseLibrary/ExercisesLibrary.js
  workout-tracker/src/views/WorkoutSession/WorkoutSession.js
  workout-tracker/src/views/WorkoutView/WorkoutView.js
Labels: Frontend

#37 Layout optimization
  workout-tracker/src/App.js
  workout-tracker/src/assets/images/logo-svg-white.svg
  workout-tracker/src/components/Logo/Logo.css
  workout-tracker/src/components/Logo/Logo.js
  workout-tracker/src/components/MainNavBar/MainNavBar.css
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.css
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.js
  workout-tracker/src/views/UserPage/DashboardNavItem.css
  workout-tracker/src/views/UserPage/DashboardNavItem.js
  workout-tracker/src/views/UserPage/UserPage.css
  workout-tracker/src/views/UserPage/UserPage.js
  workout-tracker/src/views/UserPage/UserSettings/UserSettings.js
Labels: Frontend, bug

#36 Styles css after
  workout-tracker/src/App.js
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.js
  workout-tracker/src/views/AboutUs/AboutUs.css
  workout-tracker/src/views/AboutUs/AboutUs.js
  workout-tracker/src/views/LandingPage/LandingPage.css
  workout-tracker/src/views/LandingPage/LandingPage.js
  workout-tracker/src/views/Settings/Settings.js
Labels: Frontend

#39 Change pagination
  workout-tracker/src/components/Exercises/AllExercises.js
  workout-tracker/src/store/actions/exerciseActions.js
  workout-tracker/src/store/actions/workoutsActions.js
  workout-tracker/src/store/reducers/exercises.js
  workout-tracker/src/store/reducers/workouts.js
  workout-tracker/src/views/ExerciseLibrary/ExercisesLibrary.js
  workout-tracker/src/views/WorkoutSession/WorkoutSession.js
Labels: Frontend

#42 Scrollbar fix
  workout-tracker/src/views/Settings/Settings.js
  workout-tracker/src/views/UserPage/UserPage.css
Labels: Frontend, bug

#41 Search exercises
  workout-tracker/src/components/Exercises/AllExercises.js
  workout-tracker/src/store/actions/exerciseActions.js
  workout-tracker/src/store/reducers/exercises.js
  workout-tracker/src/views/ExerciseLibrary/ExercisesLibrary.js
Labels: Frontend

#40 session duration implemented
  workout-tracker/src/views/UserPage/UserHistory/UserHistory.js
Labels: Frontend

#44 Contact pagefix
  workout-tracker/src/views/Auth/Auth.css
  workout-tracker/src/views/Auth/Login.js
  workout-tracker/src/views/Auth/Signup.js
  workout-tracker/src/views/ContactPage/ContactPage.css
  workout-tracker/src/views/ContactPage/ContactPage.js
Labels: Frontend

#46 Fix settings
  workout-tracker/src/store/actions/settingActions.js
  workout-tracker/src/store/reducers/settings.js
  workout-tracker/src/views/Settings/Settings.js
Labels: Frontend

#51 Save workout
  workout-tracker/package.json
  workout-tracker/src/App.js
  workout-tracker/src/components/Watch/Watch.js
  workout-tracker/src/index.js
  workout-tracker/src/store/actions/settingActions.js
  workout-tracker/src/store/actions/workoutsActions.js
  workout-tracker/src/store/reducers/workouts.js
  workout-tracker/src/views/UserPage/MyWorkouts/MyWorkouts.js
  workout-tracker/src/views/WorkoutSession/WorkoutSession.js
  workout-tracker/src/views/Workouts/Workouts.js
  workout-tracker/yarn.lock
Labels: Frontend

#48 Dashboard navbar
  workout-tracker/src/components/MainNavBar/MainNavBar.js
  workout-tracker/src/components/MainNavBar/MobileNavigation/MobileNavigation.css
  workout-tracker/src/components/MainNavBar/MobileNavigation/MobileNavigation.js
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.css
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.js
  workout-tracker/src/views/UserPage/DashboardNavItem.css
  workout-tracker/src/views/UserPage/UserPage.css
Labels: Frontend, enhancement

#54 Excercise Search view
  workout-tracker/src/components/Exercises/AllExercises.css
  workout-tracker/src/components/Exercises/AllExercises.js
  workout-tracker/src/views/ContactPage/ContactPage.css
Labels: Frontend

#56 Visualize user activity
  workout-tracker/src/components/Watch/Watch.js
  workout-tracker/src/store/actions/workoutsActions.js
  workout-tracker/src/store/reducers/workouts.js
  workout-tracker/src/views/UserPage/DashboardNavItem.js
  workout-tracker/src/views/UserPage/MyWorkouts/MyWorkouts.js
  workout-tracker/src/views/UserPage/Tracker/ActivityChart.js
  workout-tracker/src/views/WorkoutSession/WorkoutSession.js
  workout-tracker/src/views/Workouts/Workouts.js
Labels: Frontend

#49 side drawer close button
  workout-tracker/src/App.js
  workout-tracker/src/components/Button/Button.css
  workout-tracker/src/components/Button/Button.js
  workout-tracker/src/components/MainNavBar/MobileNavigation/MobileNavigation.css
  workout-tracker/src/components/MainNavBar/MobileNavigation/MobileNavigation.js
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.css
  workout-tracker/src/views/Auth/Login.js
  workout-tracker/src/views/Auth/Signup.js
Labels: Frontend, enhancement

#57 Excercise More Info
  workout-tracker/src/components/Exercises/AllExercises.js
  workout-tracker/src/components/Exercises/SingleExcercise.css
  workout-tracker/src/components/Exercises/SingleExercise.js
  workout-tracker/yarn.lock
Labels: Frontend

#58 fix add workout duplicates bug
  workout-tracker/src/store/reducers/workouts.js
Labels: Bug Fix, Frontend

#61 Clear localstorage
  workout-tracker/src/App.js
  workout-tracker/src/components/Exercises/AllExercises.js
  workout-tracker/src/views/ExerciseLibrary/ExercisesLibrary.js
  workout-tracker/yarn.lock
Labels: Frontend

#63 General styling workout session
  workout-tracker/src/components/Logo/Logo.js
  workout-tracker/src/components/Watch/Watch.js
  workout-tracker/src/store/actions/workoutsActions.js
  workout-tracker/src/views/Auth/Login.js
  workout-tracker/src/views/Auth/Signup.js
  workout-tracker/src/views/UserPage/MyWorkouts/MyWorkouts.js
  workout-tracker/src/views/UserPage/UserHistory/UserHistory.js
  workout-tracker/src/views/WorkoutSession/WorkoutSession.js
Labels: Frontend

#74 New style library
  workout-tracker/src/components/Exercises/AllExercises.js
  workout-tracker/src/index.js
  workout-tracker/src/store/actions/settingActions.js
  workout-tracker/src/store/reducers/exercises.js
  workout-tracker/src/views/ExerciseLibrary/ExercisesLibrary.js
  workout-tracker/src/views/Settings/Settings.js
  workout-tracker/src/views/UserPage/Tracker/ActivityChart.js
  workout-tracker/src/views/WorkoutSession/WorkoutSession.js
Labels: Frontend

#71 Profile header
  workout-tracker/src/App.js
  workout-tracker/src/components/Layout/Layout.js
  workout-tracker/src/components/MainNavBar/MainNavBar.css
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.css
  workout-tracker/src/index.css
  workout-tracker/src/views/UserPage/DashboardNavItem.css
  workout-tracker/src/views/UserPage/ProfileImage.js
  workout-tracker/src/views/UserPage/UserPage.css
  workout-tracker/src/views/UserPage/UserPage.js
Labels: Frontend, enhancement

#75 History to redux
  workout-tracker/.gitignore
  workout-tracker/package-lock.json
  workout-tracker/src/store/actions/historyActions.js
  workout-tracker/src/store/reducers/history.js
  workout-tracker/src/store/reducers/index.js
  workout-tracker/src/views/UserPage/Tracker/ActivityChart.js
  workout-tracker/src/views/UserPage/UserHistory/UserHistory.js
  workout-tracker/src/views/UserPage/UserPage.js
Labels: Frontend

#76 Weekly monthly yearly chart
  workout-tracker/src/store/reducers/history.js
  workout-tracker/src/views/UserPage/Tracker/MonthlyChart.js
  workout-tracker/src/views/UserPage/Tracker/UserTracker.js
  workout-tracker/src/views/UserPage/Tracker/WeeklyChart.js
  workout-tracker/src/views/UserPage/Tracker/YearlyChart.js
  workout-tracker/src/views/UserPage/UserHistory/UserHistory.js
Labels: Frontend

#69 Ant layout
  workout-tracker/package-lock.json
  workout-tracker/src/App.js
  workout-tracker/src/components/Layout/Layout.js
  workout-tracker/src/components/MainNavBar/MainNavBar.css
  workout-tracker/src/components/Toolbar/Toolbar.css
  workout-tracker/src/components/Toolbar/Toolbar.js
  workout-tracker/src/index.css
  workout-tracker/src/views/UserPage/UserPage.css
  workout-tracker/src/views/UserPage/UserPage.js
Labels: Frontend, enhancement

#92 Dashboard change
  workout-tracker/src/components/Layout/Layout.js
  workout-tracker/src/components/MainNavBar/MainNavBar.js
  workout-tracker/src/views/UserPage/Stats/Calendar/WorkoutCalendar.js
  workout-tracker/src/views/UserPage/Stats/Charts/MonthlyChart.js
  workout-tracker/src/views/UserPage/Stats/Charts/WeeklyChart.js
  workout-tracker/src/views/UserPage/Stats/Charts/YearlyChart.js
  workout-tracker/src/views/UserPage/Stats/Stats.js
  workout-tracker/src/views/UserPage/Stats/UserHistory/UserHistory.js
Labels: Frontend

#94 Fix dashboard design
  workout-tracker/src/views/UserPage/Stats/Calendar/WorkoutCalendar.js
  workout-tracker/src/views/UserPage/Stats/Stats.js
  workout-tracker/src/views/UserPage/Stats/UserHistory/UserHistory.js
Labels: Frontend

#95 Restyle workouts
  package-lock.json
  workout-tracker/src/App.js
  workout-tracker/src/components/Backdrop/Backdrop.css
  workout-tracker/src/components/Backdrop/Backdrop.js
  workout-tracker/src/components/Layout/Layout.js
  workout-tracker/src/components/MainNavBar/MainNavBar.js
  workout-tracker/src/components/MainNavBar/MobileNavigation/MobileNavigation.css
  workout-tracker/src/components/MainNavBar/MobileNavigation/MobileNavigation.js
  workout-tracker/src/components/MainNavBar/MobileToggle/MobileToggle.css
  workout-tracker/src/components/MainNavBar/MobileToggle/MobileToggle.js
  workout-tracker/src/components/WorkoutCard/WorkoutCard.js
  workout-tracker/src/utils/AddWorkoutButton.js
  workout-tracker/src/utils/sidebar.js
  workout-tracker/src/views/Stats/Calendar/WorkoutCalendar.js
  workout-tracker/src/views/Stats/Charts/ChartContainer.js
  workout-tracker/src/views/Stats/Charts/MonthlyChart.js
  workout-tracker/src/views/Stats/Charts/MonthlyGraph.js
  workout-tracker/src/views/Stats/Charts/WeeklyChart.js
  workout-tracker/src/views/Stats/Charts/YearlyChart.js
  workout-tracker/src/views/Stats/Charts/YearlyGraph.js
  workout-tracker/src/views/Stats/Stats.js
  workout-tracker/src/views/Stats/UserHistory/UserHistory.js
  workout-tracker/src/views/UserPage/MyWorkouts/MyWorkouts.js
  workout-tracker/src/views/UserPage/UserPage.css
  workout-tracker/src/views/UserPage/UserPage.js
  workout-tracker/src/views/Workouts/MyWorkouts/MyWorkouts.js
  workout-tracker/src/views/Workouts/WorkoutSession/WorkoutSession.js
  workout-tracker/src/views/Workouts/Workouts.js
  workout-tracker/src/views/Workouts/WorkoutsContainer.js
  workout-tracker/src/views/Workouts/customWorkout/ModalForm.js
  workout-tracker/src/views/Workouts/customWorkout/WorkoutPage.js
  workout-tracker/src/views/customWorkout/FilterTag.js
Labels: Frontend, enhancement

#103 fixed button to open modal
  workout-tracker/src/views/Workouts/MyWorkouts/MyWorkouts.js
  workout-tracker/src/views/Workouts/WorkoutsContainer.js
  workout-tracker/src/views/Workouts/customWorkout/ModalForm.js
  workout-tracker/src/views/Workouts/customWorkout/WorkoutPage.js
Labels: Frontend, enhancement

#111 Workouts updated
  workout-tracker/src/store/actions/workoutsActions.js
  workout-tracker/src/store/reducers/workouts.js
  workout-tracker/src/views/Workouts/MyWorkouts/MyWorkouts.js
  workout-tracker/src/views/Workouts/Workouts.js
Labels: Frontend

#109 Delete saved workout
  workout-tracker/src/store/actions/authenticationActions.js
Labels: Frontend

#112 add changes to index.html
  workout-tracker/public/index.html
Labels: Frontend

#116 Fe sider mobile
  workout-tracker/src/components/Layout/Layout.js
  workout-tracker/src/components/MainNavBar/SideNavigation/DashboardNavItem.js
Labels: Bug Fix, Frontend

#117 Added new exercise library
  workout-tracker/src/components/Exercises/AllExercises.js
  workout-tracker/src/index.js
  workout-tracker/src/views/customWorkout/DisplayExercise.js
Labels: Frontend

#115 Settings and Update from last PR
  workout-tracker/src/App.js
  workout-tracker/src/assets/avatar/ma.jpg
  workout-tracker/src/assets/avatar/matt.jpg
  workout-tracker/src/assets/avatar/sean.jpg
  workout-tracker/src/assets/avatar/shaun.jpg
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.js
  workout-tracker/src/views/AboutUs/AboutUs.css
  workout-tracker/src/views/AboutUs/AboutUs.js
  workout-tracker/src/views/ContactPage/ContactPage.js
  workout-tracker/src/views/Settings/Settings.js
Labels: Bug Fix, Frontend

#119 Fe bug fixes
  workout-tracker/src/App.js
  workout-tracker/src/components/Layout/Layout.js
  workout-tracker/src/components/MainNavBar/MainNavBar.css
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.css
  workout-tracker/src/components/MainNavBar/NavigationItems/NavigationItems.js
  workout-tracker/src/components/MainNavBar/SideNavigation/DashboardNavItem.js
  workout-tracker/src/views/LandingPage/LandingPage.js
  workout-tracker/src/views/Workouts/WorkoutsContainer.js
Labels: Bug Fix, Frontend, enhancement

#123 Modify custom workouts page
  workout-tracker/src/components/Exercises/AllExercises.js
  workout-tracker/src/store/actions/workoutsActions.js
  workout-tracker/src/store/reducers/workouts.js
  workout-tracker/src/utils/AddWorkoutButton.js
  workout-tracker/src/views/AboutUs/AboutUs.css
  workout-tracker/src/views/customWorkout/AllExercises.js
  workout-tracker/src/views/customWorkout/DisplayExercise.js
  workout-tracker/src/views/customWorkout/FilterExercises.js
  workout-tracker/src/views/customWorkout/ModalForm.js
  workout-tracker/src/views/customWorkout/SelectedExercises.js
  workout-tracker/src/views/customWorkout/SetsForm.js
  workout-tracker/src/views/customWorkout/SideBar.js
  workout-tracker/src/views/customWorkout/UpdateWorkoutDetails.js
Labels: enhancement

#125 Rework dashboard
  workout-tracker/src/components/Exercises/AllExercises.js
  workout-tracker/src/store/actions/chartActions.js
  workout-tracker/src/store/reducers/charts.js
  workout-tracker/src/store/reducers/index.js
  workout-tracker/src/views/Stats/Calendar/WorkoutCalendar.js
  workout-tracker/src/views/Stats/Charts/MonthlyChart.js
  workout-tracker/src/views/Stats/Charts/WeeklyChart.js
  workout-tracker/src/views/Stats/Charts/YearlyChart.js
  workout-tracker/src/views/Stats/Stats.js
  workout-tracker/src/views/Stats/UserHistory/UserHistory.js
Labels: Frontend
